# Tensor Basics

A tensor can be considered a multidimensional array.

An array may have different dimensions. A 0-dimensional array is a scalar, a 1-dimensional array is a vector, a 2-dimensional array is a matrix, and so on.

Every tensor is conformed of tensors of lower dimensions. In a way that, a 2-dimensional tensor is conformed of 1-dimensional tensors, a 3-dimensional tensor is conformed of 2-dimensional tensors, etc.

In [10]:
# Needed libraries

import tensorflow as tf
import numpy as np

# Tensor Shapes

The shape of a tensor is the number of elements that it has in each dimension. For example, a 2-dimensional tensor of shape (3, 2) has 3 elements in the first dimension and 2 elements in the second dimension.

A 0-dimensional tensor has shape ().

A 3-dimensional tensor of shape (3, 2, 4) has 3 elements in the first dimension, 2 elements in the second dimension, and 4 elements in the third dimension. In this case, the tensor has 3 two-dimensional tensors of shape (2, 4).

Another thing to is that the amount of values in a tensor's shape is the same as the tensor's number of dimensions. For example, a tensor of shape (3, 2, 4) has 3 dimensions, and a tensor of shape (3, 2) has 2 dimensions.

In [3]:
# Create a 0-dimensional tensor
zero_d = tf.constant(5)
print(zero_d)

tf.Tensor(5, shape=(), dtype=int32)


In [4]:
# Create a 1-dimensional tensor
one_d = tf.constant([1, 2, 3, 4, 5])
print(one_d)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [6]:
# Create a 2-dimensional tensor
two_d = tf.constant([[1, 2, 3], [4, 5, 6]])
print(two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [7]:
# Create a 3-dimensional tensor
three_d = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11 ,12]]])
print(three_d)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


# Casting and Converting Tensors

A tensor can be casted to another tensor of a different shape. For example, a tensor of shape (3, 2) can be casted to a tensor of shape (6, 1).


In [8]:
# Cast a tensor of shape (3, 2) to a tensor of shape (6, 1)
two_d = tf.constant([[1, 2], [3, 4], [5, 6]]) # shape (3, 2)    
six_one = tf.reshape(two_d, (6, 1)) # shape (6, 1)
print(six_one)

tf.Tensor(
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]], shape=(6, 1), dtype=int32)


We can also convert a tensor to a tensor of a different shape. For example, a tensor of shape (3, 2) can be converted to a tensor of shape (2, 3).

In [9]:
# Convert a tensor of shape (3, 2) to a tensor of shape (2, 3)
two_d = tf.constant([[1, 2], [3, 4], [5, 6]]) # shape (3, 2)
two_three = tf.reshape(two_d, (2, 3)) # shape (2, 3)

Another thing, is that we can convert a numpy array to a tensor and vice versa.

In [11]:
# Convert a numpy array to a tensor
numpy_tensor = np.array([1, 2, 3, 4, 5, 6])
converted_tensor = tf.convert_to_tensor(numpy_tensor, dtype=tf.float64)
print(converted_tensor)

tf.Tensor([1. 2. 3. 4. 5. 6.], shape=(6,), dtype=float64)


In [13]:
# Convert a tensor to a numpy array
two_d = tf.constant([[1, 2], [3, 4], [5, 6]]) # shape (3, 2)
numpy_array = two_d.numpy()
print(numpy_array)

[[1 2]
 [3 4]
 [5 6]]


# Eye tensors

An eye tensor is a tensor that has 1s in its diagonal and 0s in the rest of its elements. For example, a 3x3 eye tensor is:

\begin{matrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{matrix}



In [14]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
